services:
  - type: web
    name: peptideiq
    env: python
    region: oregon
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      python rpm2cpio.py tmp/wkhtmltox.rpm tmp/
      cp tmp/usr/local/bin/wkhtmltopdf bin/
    startCommand: gunicorn app:app
    envVars:
      - key: FLASK_ENV
        value: production
