services:
  - type: web
    name: peptideiq
    env: python
    region: oregon
    plan: free
    buildCommand: |
      pip install cpioextract
      ./build.sh
      pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: FLASK_ENV
        value: production